eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
server:
  port: 8767
spring:
  application:
    name: rabbitmq
  #以下为rabbitmq配置
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: user
    password: 123456
    virtual-host: /my_db
